---

- name: install rsyslog
  package:
    name=rsyslog
    state=present

- name: configure rsyslog
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.conf
  notify:
    - reload rsyslog
  tags: rsyslog

- name: add forwarding template
  template: src=forwarding.conf.j2 dest=/etc/rsyslog.d/30-forwarding.conf
  when: rsyslog_forwarding == true
  notify:
    - reload rsyslog
  tags: rsyslog
